name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^3.1.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true